name = "AcademicIdentifiers"
uuid = "73aec6e9-1368-4429-b03d-50b89ba0733e"
authors = ["TEC <git@tecosaur.net>"]
version = "0.1.0"

[deps]
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[extensions]
StructTypesExt = "StructTypes"

[weakdeps]
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
julia = "1.9"
StyledStrings = "1"
StructTypes = "1"
