name = "AcademicIdentifiers"
uuid = "73aec6e9-1368-4429-b03d-50b89ba0733e"
version = "0.1.0"
authors = ["TEC <contact@tecosaur.net>"]

[weakdeps]
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[extensions]
StructTypesExt = "StructTypes"
PrettyPrintExt = "StyledStrings"

[compat]
StructTypes = "1"
StyledStrings = "1"
julia = "1.9"

[extras]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["StyledStrings", "Test", "JSON3"]
