name = "AcademicIdentifiers"
uuid = "73aec6e9-1368-4429-b03d-50b89ba0733e"
version = "0.1.0"
authors = ["TEC <contact@tecosaur.net>"]

[deps]
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[weakdeps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[extensions]
JsonExt = "JSON"
StructTypesExt = "StructTypes"

[compat]
JSON = "1"
StructTypes = "1"
StyledStrings = "1"
julia = "1.9"

[extras]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "JSON", "JSON3"]
