name = "AcademicIdentifiers"
uuid = "73aec6e9-1368-4429-b03d-50b89ba0733e"
version = "0.1.0"
authors = ["TEC <contact@tecosaur.net>"]

[deps]
DigitalIdentifiersBase = "4753c187-0528-4cab-a788-b8a80107dae0"

[sources]
DigitalIdentifiersBase = {rev = "main", url = "https://code.tecosaur.net/tec/DigitalIdentifiersBase.jl.git"}

[compat]
DigitalIdentifiersBase = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
